type ShaderOptionKind = 'range' | 'toggle' | 'color' | 'select';

type ShaderOptionControl = {
  id: string;
  label: string;
  description?: string;
  kind: ShaderOptionKind;
  value: number | boolean | string;
  min?: number;
  max?: number;
  step?: number;
  options?: string[];
};

type ShaderOptionSection = {
  title: string;
  controls: ShaderOptionControl[];
};

type ShaderOptionCategory = {
  id: string;
  title: string;
  summary: string;
  sections: ShaderOptionSection[];
};

export const shaderLightingOptionGroups: ShaderOptionCategory[] = [
  {
    id: 'sunlight',
    title: 'Sunlight',
    summary: 'Direct daytime light, sky tint, exposure response, and sun angle behavior.',
    sections: [
      {
        title: 'Color and intensity',
        controls: [
          {
            id: 'sunlight-enabled',
            label: 'Enable sunlight pass',
            description: 'Turns direct sun lighting on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'sunlight-intensity',
            label: 'Sun intensity',
            description: 'Controls the brightness of direct sunlight.',
            kind: 'range',
            value: 1.1,
            min: 0,
            max: 3,
            step: 0.05,
          },
          {
            id: 'sunlight-temperature',
            label: 'Color temperature',
            description: 'Warms or cools the sunlight color.',
            kind: 'range',
            value: 6200,
            min: 2500,
            max: 9000,
            step: 50,
          },
          {
            id: 'sunlight-tint',
            label: 'Sun tint',
            description: 'Sets the custom color tint for sunlight.',
            kind: 'color',
            value: '#fff2cf',
          },
          {
            id: 'sunlight-saturation',
            label: 'Light saturation',
            description: 'Adjusts how vivid sunlight colors appear.',
            kind: 'range',
            value: 0.18,
            min: -1,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Sky interaction',
        controls: [
          {
            id: 'sunlight-sky-scatter',
            label: 'Sky scattering',
            description: 'Blends sunlight color into the sky.',
            kind: 'range',
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-horizon-warmth',
            label: 'Horizon warmth',
            description: 'Adds warmer light near the horizon.',
            kind: 'range',
            value: 0.42,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-zenith-falloff',
            label: 'Zenith falloff',
            description: 'Reduces sun color at the top of the sky.',
            kind: 'range',
            value: 0.35,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-cloud-dimming',
            label: 'Cloud dimming',
            description: 'Dims sunlight when clouds cover the sky.',
            kind: 'range',
            value: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-weather-response',
            label: 'Weather response',
            description: 'Chooses how sunlight reacts to weather.',
            kind: 'select',
            value: 'Balanced',
            options: ['Off', 'Soft', 'Balanced', 'Dramatic'],
          },
        ],
      },
      {
        title: 'Time of day',
        controls: [
          {
            id: 'sunlight-dawn-boost',
            label: 'Dawn boost',
            description: 'Increases sunlight brightness at dawn.',
            kind: 'range',
            value: 0.35,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-noon-crispness',
            label: 'Noon crispness',
            description: 'Sharpens midday light and contrast.',
            kind: 'range',
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-sunset-warmth',
            label: 'Sunset warmth',
            description: 'Adds golden color during sunset.',
            kind: 'range',
            value: 0.72,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-low-angle-strength',
            label: 'Low angle strength',
            description: 'Boosts sun light at low angles.',
            kind: 'range',
            value: 0.44,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'sunlight-time-blending',
            label: 'Time blending',
            description: 'Controls transitions between day phases.',
            kind: 'select',
            value: 'Smooth',
            options: ['Instant', 'Smooth', 'Cinematic'],
          },
        ],
      },
    ],
  },
  {
    id: 'moonlight',
    title: 'Moonlight',
    summary: 'Night lighting controls for moon color, strength, visibility, and sky response.',
    sections: [
      {
        title: 'Color and strength',
        controls: [
          {
            id: 'moonlight-enabled',
            label: 'Enable moonlight pass',
            description: 'Turns moon lighting on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'moonlight-intensity',
            label: 'Moon intensity',
            description: 'Controls the brightness of moonlight.',
            kind: 'range',
            value: 0.42,
            min: 0,
            max: 2,
            step: 0.02,
          },
          {
            id: 'moonlight-tint',
            label: 'Moon tint',
            description: 'Sets the custom color tint for moonlight.',
            kind: 'color',
            value: '#b8ccff',
          },
          {
            id: 'moonlight-blue-shift',
            label: 'Blue shift',
            description: 'Pushes night light toward cooler blue tones.',
            kind: 'range',
            value: 0.46,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-saturation',
            label: 'Night saturation',
            description: 'Adjusts color intensity during night.',
            kind: 'range',
            value: -0.18,
            min: -1,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Night visibility',
        controls: [
          {
            id: 'moonlight-ambient-floor',
            label: 'Ambient floor',
            description: 'Sets the minimum ambient light at night.',
            kind: 'range',
            value: 0.16,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-contrast',
            label: 'Night contrast',
            description: 'Controls contrast between lit and dark areas.',
            kind: 'range',
            value: 0.54,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-cave-leak',
            label: 'Cave light leak',
            description: 'Lets a small amount of moonlight enter caves.',
            kind: 'range',
            value: 0.08,
            min: 0,
            max: 0.5,
            step: 0.01,
          },
          {
            id: 'moonlight-minimum-luminance',
            label: 'Minimum luminance',
            description: 'Prevents night scenes from becoming fully black.',
            kind: 'range',
            value: 0.08,
            min: 0,
            max: 0.4,
            step: 0.01,
          },
          {
            id: 'moonlight-visibility-style',
            label: 'Visibility style',
            description: 'Chooses the overall readability of night scenes.',
            kind: 'select',
            value: 'Natural',
            options: ['Dark', 'Natural', 'Readable', 'Bright'],
          },
        ],
      },
      {
        title: 'Moon phase',
        controls: [
          {
            id: 'moonlight-phase-enabled',
            label: 'Use moon phase',
            description: 'Changes moonlight based on the current phase.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'moonlight-new-moon-dimming',
            label: 'New moon dimming',
            description: 'Reduces light during a new moon.',
            kind: 'range',
            value: 0.65,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-full-moon-boost',
            label: 'Full moon boost',
            description: 'Increases light during a full moon.',
            kind: 'range',
            value: 0.28,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-cloud-occlusion',
            label: 'Cloud occlusion',
            description: 'Dims moonlight when clouds pass overhead.',
            kind: 'range',
            value: 0.38,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'moonlight-phase-response',
            label: 'Phase response',
            description: 'Sets how strongly phases affect moonlight.',
            kind: 'select',
            value: 'Balanced',
            options: ['Subtle', 'Balanced', 'Strong'],
          },
        ],
      },
    ],
  },
  {
    id: 'block-light',
    title: 'Block Light',
    summary: 'Torch, lantern, lava, and artificial light response for nearby blocks.',
    sections: [
      {
        title: 'Core light',
        controls: [
          {
            id: 'block-light-enabled',
            label: 'Enable block lighting',
            description: 'Turns block-emitted lighting on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'block-light-intensity',
            label: 'Block light intensity',
            description: 'Controls brightness from light-emitting blocks.',
            kind: 'range',
            value: 1,
            min: 0,
            max: 3,
            step: 0.05,
          },
          {
            id: 'block-light-radius',
            label: 'Light radius',
            description: 'Adjusts how far block light reaches.',
            kind: 'range',
            value: 1.15,
            min: 0.25,
            max: 3,
            step: 0.05,
          },
          {
            id: 'block-light-falloff',
            label: 'Falloff curve',
            description: 'Changes how quickly block light fades.',
            kind: 'range',
            value: 1.65,
            min: 0.5,
            max: 4,
            step: 0.05,
          },
          {
            id: 'block-light-color-mode',
            label: 'Color mode',
            description: 'Chooses how block light colors are assigned.',
            kind: 'select',
            value: 'Per block',
            options: ['Vanilla', 'Warm', 'Per block', 'Custom'],
          },
        ],
      },
      {
        title: 'Warm sources',
        controls: [
          {
            id: 'block-light-torch-tint',
            label: 'Torch tint',
            description: 'Sets the color used by torch light.',
            kind: 'color',
            value: '#ffb15c',
          },
          {
            id: 'block-light-lantern-tint',
            label: 'Lantern tint',
            description: 'Sets the color used by lantern light.',
            kind: 'color',
            value: '#ffd38a',
          },
          {
            id: 'block-light-lava-tint',
            label: 'Lava tint',
            description: 'Sets the color used by lava light.',
            kind: 'color',
            value: '#ff6a24',
          },
          {
            id: 'block-light-fire-flicker',
            label: 'Fire flicker',
            description: 'Controls animated brightness variation for fire.',
            kind: 'range',
            value: 0.32,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'block-light-heat-glow',
            label: 'Heat glow',
            description: 'Adds warm glow around hot light sources.',
            kind: 'range',
            value: 0.45,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Artificial sources',
        controls: [
          {
            id: 'block-light-redstone-tint',
            label: 'Redstone tint',
            description: 'Sets the color used by redstone light.',
            kind: 'color',
            value: '#ff2d2d',
          },
          {
            id: 'block-light-soul-tint',
            label: 'Soul light tint',
            description: 'Sets the color used by soul fire lights.',
            kind: 'color',
            value: '#5fe7ff',
          },
          {
            id: 'block-light-end-tint',
            label: 'End light tint',
            description: 'Sets the color used by End-themed lights.',
            kind: 'color',
            value: '#d7a4ff',
          },
          {
            id: 'block-light-colored-lamps',
            label: 'Colored lamp support',
            description: 'Uses lamp block colors for emitted light.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'block-light-artificial-balance',
            label: 'Artificial balance',
            description: 'Balances artificial lights against natural light.',
            kind: 'range',
            value: 0.55,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    id: 'shadows',
    title: 'Shadows',
    summary: 'Directional shadow maps, contact shadows, softness, distance, and filtering.',
    sections: [
      {
        title: 'Shadow maps',
        controls: [
          {
            id: 'shadows-enabled',
            label: 'Enable shadows',
            description: 'Turns shader shadow rendering on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'shadows-resolution',
            label: 'Shadow resolution',
            description: 'Sets the detail level of shadow maps.',
            kind: 'select',
            value: '2048',
            options: ['1024', '2048', '4096', '8192'],
          },
          {
            id: 'shadows-distance',
            label: 'Shadow distance',
            description: 'Controls how far shadows are rendered.',
            kind: 'range',
            value: 128,
            min: 32,
            max: 512,
            step: 8,
          },
          {
            id: 'shadows-distortion',
            label: 'Shadow focus',
            description: 'Concentrates shadow-map resolution near the camera for crisper close shadows.',
            kind: 'range',
            value: 0.6,
            min: 0,
            max: 0.95,
            step: 0.01,
          },
          {
            id: 'shadows-fade',
            label: 'Distance fade',
            description: 'Width of the band where shadows fade out at the shadow distance limit.',
            kind: 'range',
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Softness and contact',
        controls: [
          {
            id: 'shadows-softness',
            label: 'Shadow softness',
            description: 'Controls how soft shadow edges appear.',
            kind: 'range',
            value: 0.48,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'shadows-contact-enabled',
            label: 'Contact shadows',
            description: 'Adds small shadows where surfaces touch.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'shadows-contact-length',
            label: 'Contact length',
            description: 'Sets how far contact shadows extend.',
            kind: 'range',
            value: 0.34,
            min: 0,
            max: 2,
            step: 0.01,
          },
          {
            id: 'shadows-contact-opacity',
            label: 'Contact opacity',
            description: 'Controls darkness of contact shadows.',
            kind: 'range',
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'shadows-filter',
            label: 'Shadow filter',
            description: 'Chooses the shadow smoothing technique.',
            kind: 'select',
            value: 'Variable penumbra',
            options: ['Nearest', 'PCF', 'Soft PCF', 'Variable penumbra'],
          },
        ],
      },
      {
        title: 'Stability',
        controls: [
          {
            id: 'shadows-bias',
            label: 'Depth bias',
            description: 'Offsets shadows to reduce surface acne.',
            kind: 'range',
            value: 0.05,
            min: 0,
            max: 0.3,
            step: 0.005,
          },
          {
            id: 'shadows-normal-bias',
            label: 'Normal bias',
            description: 'Offsets shadows along surface normals.',
            kind: 'range',
            value: 0.18,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'shadows-texel-snap',
            label: 'Texel snapping',
            description: 'Stabilizes shadows while the camera moves.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'shadows-sun-path-tilt',
            label: 'Sun path tilt',
            description: 'Tilts the sun path sideways so noon shadows are not directly underneath blocks.',
            kind: 'range',
            value: -32,
            min: -60,
            max: 60,
            step: 1,
          },
          {
            id: 'shadows-leak-fix',
            label: 'Light leak reduction',
            description: 'Reduces stray light through shadowed edges.',
            kind: 'range',
            value: 0.38,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    id: 'ambient-occlusion',
    title: 'Ambient Occlusion',
    summary: 'Screen-space and world-space crevice shading for depth and material grounding.',
    sections: [
      {
        title: 'Occlusion model',
        controls: [
          {
            id: 'ambient-occlusion-enabled',
            label: 'Enable ambient occlusion',
            description: 'Turns crevice and corner shading on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'ambient-occlusion-method',
            label: 'AO method',
            description: 'Chooses the ambient occlusion algorithm.',
            kind: 'select',
            value: 'GTAO',
            options: ['SSAO', 'HBAO', 'GTAO', 'Hybrid'],
          },
          {
            id: 'ambient-occlusion-strength',
            label: 'AO strength',
            description: 'Controls the darkness of occluded areas.',
            kind: 'range',
            value: 0.68,
            min: 0,
            max: 2,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-radius',
            label: 'AO radius',
            description: 'Sets how far occlusion searches nearby geometry.',
            kind: 'range',
            value: 0.82,
            min: 0.05,
            max: 4,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-power',
            label: 'AO power',
            description: 'Shapes the contrast of occlusion shading.',
            kind: 'range',
            value: 1.35,
            min: 0.25,
            max: 4,
            step: 0.05,
          },
        ],
      },
      {
        title: 'Quality',
        controls: [
          {
            id: 'ambient-occlusion-samples',
            label: 'AO samples',
            description: 'Sets sample count for occlusion quality.',
            kind: 'select',
            value: '16',
            options: ['8', '16', '32', '64'],
          },
          {
            id: 'ambient-occlusion-denoise',
            label: 'Denoise strength',
            description: 'Smooths noisy ambient occlusion results.',
            kind: 'range',
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-edge-preserve',
            label: 'Edge preserve',
            description: 'Keeps occlusion from bleeding across edges.',
            kind: 'range',
            value: 0.7,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-dither',
            label: 'Noise dithering',
            description: 'Rotates the sample pattern per pixel to hide banding.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'ambient-occlusion-distance-fade',
            label: 'Distance fade',
            description: 'Fades occlusion out with distance from the camera.',
            kind: 'range',
            value: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Scene response',
        controls: [
          {
            id: 'ambient-occlusion-grass-damping',
            label: 'Grass damping',
            description: 'Reduces heavy occlusion on grass surfaces.',
            kind: 'range',
            value: 0.36,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-water-ignore',
            label: 'Ignore water surfaces',
            description: 'Prevents water from receiving occlusion shading.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'ambient-occlusion-cave-boost',
            label: 'Cave boost',
            description: 'Increases occlusion strength in cave areas.',
            kind: 'range',
            value: 0.44,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-sky-fade',
            label: 'Sky fade',
            description: 'Fades occlusion near open sky lighting.',
            kind: 'range',
            value: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'ambient-occlusion-material-bias',
            label: 'Material bias',
            description: 'Chooses how materials influence occlusion.',
            kind: 'select',
            value: 'Balanced',
            options: ['Soft', 'Balanced', 'Strong', 'Per material'],
          },
        ],
      },
    ],
  },
  {
    id: 'global-illumination',
    title: 'Global Illumination',
    summary: 'Indirect light bounce, color bleeding, probe behavior, and screen-space fallback.',
    sections: [
      {
        title: 'Bounce lighting',
        controls: [
          {
            id: 'global-illumination-enabled',
            label: 'Enable global illumination',
            description: 'Turns indirect bounce lighting on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'global-illumination-method',
            label: 'GI method',
            description: 'Chooses the global illumination technique.',
            kind: 'select',
            value: 'Screen space',
            options: ['Off', 'Ambient bounce', 'Screen space', 'Hybrid'],
          },
          {
            id: 'global-illumination-strength',
            label: 'GI strength',
            description: 'Controls brightness of bounced light.',
            kind: 'range',
            value: 0.72,
            min: 0,
            max: 2,
            step: 0.01,
          },
          {
            id: 'global-illumination-bounce-count',
            label: 'Bounce count',
            description: 'Sets how many light bounces are simulated.',
            kind: 'select',
            value: '1',
            options: ['1', '2', '3'],
          },
          {
            id: 'global-illumination-color-bleed',
            label: 'Color bleeding',
            description: 'Controls color transfer between nearby surfaces.',
            kind: 'range',
            value: 0.48,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Sampling',
        controls: [
          {
            id: 'global-illumination-samples',
            label: 'GI samples',
            description: 'Sets sample count for indirect lighting.',
            kind: 'select',
            value: '16',
            options: ['8', '16', '32', '64'],
          },
          {
            id: 'global-illumination-ray-length',
            label: 'Ray length',
            description: 'Controls how far GI rays search.',
            kind: 'range',
            value: 24,
            min: 4,
            max: 128,
            step: 1,
          },
          {
            id: 'global-illumination-thickness',
            label: 'Scene thickness',
            description: 'Helps GI understand thin scene surfaces.',
            kind: 'range',
            value: 0.38,
            min: 0.01,
            max: 2,
            step: 0.01,
          },
          {
            id: 'global-illumination-denoise',
            label: 'GI denoise',
            description: 'Smooths noisy indirect lighting.',
            kind: 'range',
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'global-illumination-distance-fade',
            label: 'Distance fade',
            description: 'Fades indirect light gathering out with distance.',
            kind: 'range',
            value: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Interior and exterior',
        controls: [
          {
            id: 'global-illumination-cave-fill',
            label: 'Cave fill light',
            description: 'Adds soft indirect light inside caves.',
            kind: 'range',
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'global-illumination-sky-bounce',
            label: 'Sky bounce',
            description: 'Adds bounced light from the sky.',
            kind: 'range',
            value: 0.4,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'global-illumination-block-bounce',
            label: 'Block light bounce',
            description: 'Lets block lights contribute to bounced light.',
            kind: 'range',
            value: 0.34,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'global-illumination-leak-reduction',
            label: 'Leak reduction',
            description: 'Reduces indirect light leaking through walls.',
            kind: 'range',
            value: 0.56,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'global-illumination-indoor-mode',
            label: 'Indoor response',
            description: 'Chooses how GI brightens interior spaces.',
            kind: 'select',
            value: 'Balanced',
            options: ['Dark', 'Balanced', 'Readable', 'Bright'],
          },
        ],
      },
    ],
  },
  {
    id: 'emissive-light',
    title: 'Emissive Light',
    summary: 'Material emission, animated glow, item highlights, and emissive light spill.',
    sections: [
      {
        title: 'Emission',
        controls: [
          {
            id: 'emissive-light-enabled',
            label: 'Enable emissive lighting',
            description: 'Turns material emission lighting on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'emissive-light-strength',
            label: 'Emission strength',
            description: 'Controls brightness from emissive materials.',
            kind: 'range',
            value: 0.85,
            min: 0,
            max: 3,
            step: 0.05,
          },
          {
            id: 'emissive-light-radius',
            label: 'Emission radius',
            description: 'Adjusts how far emissive glow reaches.',
            kind: 'range',
            value: 0.7,
            min: 0,
            max: 3,
            step: 0.05,
          },
          {
            id: 'emissive-light-falloff',
            label: 'Emission falloff',
            description: 'Changes how emissive light fades with distance.',
            kind: 'range',
            value: 1.45,
            min: 0.25,
            max: 4,
            step: 0.05,
          },
          {
            id: 'emissive-light-source-mode',
            label: 'Source mode',
            description: 'Chooses which materials emit light.',
            kind: 'select',
            value: 'Material map',
            options: ['Off', 'Whitelist', 'Material map', 'Auto detect'],
          },
        ],
      },
      {
        title: 'Materials',
        controls: [
          {
            id: 'emissive-light-ore-glow',
            label: 'Ore glow',
            description: 'Controls glow strength for ore materials.',
            kind: 'range',
            value: 0.38,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'emissive-light-plant-glow',
            label: 'Plant glow',
            description: 'Controls subtle glow on plant materials.',
            kind: 'range',
            value: 0.16,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'emissive-light-entity-eyes',
            label: 'Entity eye glow',
            description: 'Enables glowing eyes on supported entities.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'emissive-light-item-glow',
            label: 'Held item glow',
            description: 'Controls glow cast by held items.',
            kind: 'range',
            value: 0.3,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'emissive-light-custom-tint',
            label: 'Custom emission tint',
            description: 'Sets a shared tint for custom emissions.',
            kind: 'color',
            value: '#fff0b0',
          },
        ],
      },
      {
        title: 'Animation',
        controls: [
          {
            id: 'emissive-light-pulse-enabled',
            label: 'Pulse animation',
            description: 'Animates emissive brightness over time.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'emissive-light-pulse-speed',
            label: 'Pulse speed',
            description: 'Controls how fast emissive pulsing moves.',
            kind: 'range',
            value: 0.35,
            min: 0,
            max: 3,
            step: 0.05,
          },
          {
            id: 'emissive-light-pulse-depth',
            label: 'Pulse depth',
            description: 'Sets how strong the emission pulse is.',
            kind: 'range',
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'emissive-light-flicker',
            label: 'Micro flicker',
            description: 'Adds small random variation to emissive light.',
            kind: 'range',
            value: 0.12,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'emissive-light-animation-style',
            label: 'Animation style',
            description: 'Chooses the feel of emissive animation.',
            kind: 'select',
            value: 'Subtle',
            options: ['Off', 'Subtle', 'Alive', 'Arcade'],
          },
        ],
      },
    ],
  },
  {
    id: 'bloom',
    title: 'Bloom',
    summary: 'Bright highlight glow, thresholding, blur shape, lens response, and tone safety.',
    sections: [
      {
        title: 'Threshold and strength',
        controls: [
          {
            id: 'bloom-enabled',
            label: 'Enable bloom',
            description: 'Turns bright highlight glow on or off.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'bloom-threshold',
            label: 'Bloom threshold',
            description: 'Sets how bright pixels must be to bloom.',
            kind: 'range',
            value: 1.15,
            min: 0,
            max: 4,
            step: 0.01,
          },
          {
            id: 'bloom-intensity',
            label: 'Bloom intensity',
            description: 'Controls the strength of bloom glow.',
            kind: 'range',
            value: 0.42,
            min: 0,
            max: 2,
            step: 0.01,
          },
          {
            id: 'bloom-soft-knee',
            label: 'Soft knee',
            description: 'Smooths the bloom threshold transition.',
            kind: 'range',
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-source-bias',
            label: 'Source bias',
            description: 'Chooses which bright sources create bloom.',
            kind: 'select',
            value: 'Highlights',
            options: ['All bright pixels', 'Highlights', 'Emissive only', 'Sun and emissive'],
          },
        ],
      },
      {
        title: 'Blur shape',
        controls: [
          {
            id: 'bloom-radius',
            label: 'Bloom radius',
            description: 'Controls how far bloom spreads outward.',
            kind: 'range',
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-quality',
            label: 'Bloom quality',
            description: 'Sets blur quality for bloom rendering.',
            kind: 'select',
            value: 'High',
            options: ['Low', 'Medium', 'High', 'Ultra'],
          },
          {
            id: 'bloom-diffusion',
            label: 'Diffusion',
            description: 'Softens bloom into surrounding pixels.',
            kind: 'range',
            value: 0.48,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-anamorphic',
            label: 'Anamorphic stretch',
            description: 'Stretches bloom horizontally like a lens flare.',
            kind: 'range',
            value: 0.12,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-ghosting',
            label: 'Ghosting control',
            description: 'Controls secondary bloom ghost artifacts.',
            kind: 'range',
            value: 0.24,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: 'Color and safety',
        controls: [
          {
            id: 'bloom-tint',
            label: 'Bloom tint',
            description: 'Sets the color tint applied to bloom.',
            kind: 'color',
            value: '#fff7df',
          },
          {
            id: 'bloom-color-preserve',
            label: 'Color preservation',
            description: 'Keeps original colors visible inside bloom.',
            kind: 'range',
            value: 0.74,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-firefly-rejection',
            label: 'Firefly rejection',
            description: 'Suppresses tiny overbright sparkle artifacts.',
            kind: 'range',
            value: 0.66,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: 'bloom-exposure-protection',
            label: 'Exposure protection',
            description: 'Prevents bloom from overpowering exposure.',
            kind: 'toggle',
            value: true,
          },
          {
            id: 'bloom-night-limit',
            label: 'Night bloom limit',
            description: 'Limits bloom strength in dark scenes.',
            kind: 'range',
            value: 0.5,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
];
