export const shaderAtmosphereOptionGroups = [
  {
    id: "sky",
    title: "Sky",
    summary: "Shape the base sky gradient, horizon color, sun tint, and exposure.",
    sections: [
      {
        title: "Gradient",
        controls: [
          {
            id: "sky-zenith-color",
            label: "Zenith color",
            description: "Sets the color at the top of the sky.",
            kind: "color",
            value: "#6ca8ff",
          },
          {
            id: "sky-horizon-color",
            label: "Horizon color",
            description: "Sets the color near the horizon line.",
            kind: "color",
            value: "#d8efff",
          },
          {
            id: "sky-gradient-strength",
            label: "Gradient strength",
            description: "Controls how strongly sky colors blend.",
            kind: "range",
            value: 0.72,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "sky-horizon-height",
            label: "Horizon height",
            description: "Moves the horizon band higher or lower.",
            kind: "range",
            value: 0.38,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "Sun And Moon",
        controls: [
          {
            id: "sky-sun-glow",
            label: "Sun glow",
            description: "Adjusts the soft halo around the sun.",
            kind: "range",
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "sky-sun-size",
            label: "Sun size",
            description: "Changes the visible size of the sun disk.",
            kind: "range",
            value: 0.34,
            min: 0.05,
            max: 1,
            step: 0.01,
          },
          {
            id: "sky-moon-brightness",
            label: "Moon brightness",
            description: "Controls how bright the moon appears at night.",
            kind: "range",
            value: 0.42,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "sky-celestial-style",
            label: "Celestial style",
            description: "Chooses the rendering style for sun and moon.",
            kind: "select",
            value: "soft disk",
            options: ["soft disk", "sharp vanilla", "cinematic glow", "realistic"],
          },
        ],
      },
      {
        title: "Exposure",
        controls: [
          {
            id: "sky-exposure",
            label: "Exposure",
            description: "Adjusts overall brightness of the sky.",
            kind: "range",
            value: 1,
            min: 0.25,
            max: 2,
            step: 0.01,
          },
          {
            id: "sky-saturation",
            label: "Saturation",
            description: "Controls how vivid sky colors appear.",
            kind: "range",
            value: 0.64,
            min: 0,
            max: 1.5,
            step: 0.01,
          },
          {
            id: "sky-banding-fix",
            label: "Dither sky banding",
            description: "Reduces visible bands in smooth sky gradients.",
            kind: "toggle",
            value: true,
            minVersion: "1.21",
          },
          {
            id: "sky-vanilla-blend",
            label: "Blend with vanilla sky",
            description: "Mixes custom sky color with the vanilla sky.",
            kind: "range",
            value: 0.18,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    id: "clouds",
    title: "Clouds",
    summary: "Tune cloud layers, lighting response, movement, and cover density.",
    sections: [
      {
        title: "Layering",
        controls: [
          {
            id: "clouds-style",
            label: "Cloud style",
            description: "Chooses the overall shape and rendering of clouds.",
            kind: "select",
            value: "volumetric soft",
            options: ["vanilla flat", "painted", "volumetric soft", "storm shelf"],
          },
          {
            id: "clouds-density",
            label: "Density",
            description: "Controls how much of the sky clouds cover.",
            kind: "range",
            value: 0.46,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-height",
            label: "Height",
            description: "Moves cloud layers higher or lower in the sky.",
            kind: "range",
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-depth",
            label: "Layer depth",
            description: "Sets how thick layered clouds appear.",
            kind: "range",
            value: 0.38,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "Motion",
        controls: [
          {
            id: "clouds-speed",
            label: "Wind speed",
            description: "Controls how quickly clouds move across the sky.",
            kind: "range",
            value: 0.24,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-direction",
            label: "Wind direction",
            description: "Sets the direction clouds travel.",
            kind: "range",
            value: 45,
            min: 0,
            max: 360,
            step: 1,
          },
          {
            id: "clouds-turbulence",
            label: "Turbulence",
            description: "Adds breakup and uneven motion to clouds.",
            kind: "range",
            value: 0.36,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-weather-sync",
            label: "Sync with weather",
            description: "Lets cloud cover react to current weather.",
            kind: "toggle",
            value: true,
          },
        ],
      },
      {
        title: "Lighting",
        controls: [
          {
            id: "clouds-sun-scatter",
            label: "Sun scattering",
            description: "Controls how much sunlight glows through clouds.",
            kind: "range",
            value: 0.66,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-shadowing",
            label: "Self shadowing",
            description: "Adds internal shadows inside cloud layers.",
            kind: "range",
            value: 0.42,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "clouds-night-tint",
            label: "Night tint",
            description: "Sets the color clouds take on at night.",
            kind: "color",
            value: "#52617d",
          },
          {
            id: "clouds-silver-lining",
            label: "Silver lining",
            description: "Adds bright sunlit rims to cloud edges.",
            kind: "toggle",
            value: true,
            minVersion: "1.21",
          },
        ],
      },
    ],
  },
  {
    id: "fog",
    title: "Fog",
    summary: "Control atmospheric depth, distance haze, biome tinting, and low mist.",
    sections: [
      {
        title: "Distance Fog",
        controls: [
          {
            id: "fog-mode",
            label: "Fog mode",
            description: "Chooses how distance fog is calculated.",
            kind: "select",
            value: "height aware",
            options: ["off", "vanilla", "height aware", "cinematic"],
          },
          {
            id: "fog-density",
            label: "Density",
            description: "Controls how thick the distance fog appears.",
            kind: "range",
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "fog-start",
            label: "Start distance",
            description: "Sets how soon fog begins from the camera.",
            kind: "range",
            value: 0.18,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "fog-falloff",
            label: "Falloff",
            description: "Controls how quickly fog builds with distance.",
            kind: "range",
            value: 0.64,
            min: 0.1,
            max: 3,
            step: 0.01,
          },
        ],
      },
      {
        title: "Color",
        controls: [
          {
            id: "fog-day-color",
            label: "Day fog color",
            description: "Sets the fog color used during daytime.",
            kind: "color",
            value: "#b9d8ef",
          },
          {
            id: "fog-night-color",
            label: "Night fog color",
            description: "Sets the fog color used at night.",
            kind: "color",
            value: "#25304a",
          },
          {
            id: "fog-biome-tint",
            label: "Biome tint blend",
            description: "Blends biome colors into the fog.",
            kind: "range",
            value: 0.44,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "fog-sky-color-lock",
            label: "Match sky gradient",
            description: "Keeps fog color aligned with the sky gradient.",
            kind: "toggle",
            value: true,
          },
        ],
      },
      {
        title: "Ground Mist",
        controls: [
          {
            id: "fog-ground-mist",
            label: "Ground mist",
            description: "Adds low fog close to the terrain.",
            kind: "toggle",
            value: true,
          },
          {
            id: "fog-mist-height",
            label: "Mist height",
            description: "Controls how high ground mist rises.",
            kind: "range",
            value: 0.28,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "fog-mist-noise",
            label: "Mist breakup",
            description: "Adds noise variation to ground mist.",
            kind: "range",
            value: 0.52,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "fog-waterfall-boost",
            label: "Boost near water",
            description: "Increases mist around wet or water-heavy areas.",
            kind: "toggle",
            value: false,
          },
        ],
      },
    ],
  },
  {
    id: "weather",
    title: "Weather",
    summary: "Adjust rain, snow, storms, wet surfaces, and weather lighting mood.",
    sections: [
      {
        title: "Rain",
        controls: [
          {
            id: "weather-rain-opacity",
            label: "Rain opacity",
            description: "Controls how visible rain streaks are.",
            kind: "range",
            value: 0.64,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "weather-rain-angle",
            label: "Rain angle",
            description: "Tilts rain streaks to imply wind direction.",
            kind: "range",
            value: 12,
            min: -45,
            max: 45,
            step: 1,
          },
          {
            id: "weather-rain-splash",
            label: "Rain splashes",
            description: "Shows splash effects where rain hits surfaces.",
            kind: "toggle",
            value: true,
          },
          {
            id: "weather-rain-streak-style",
            label: "Streak style",
            description: "Chooses the visual style for falling rain.",
            kind: "select",
            value: "thin",
            options: ["vanilla", "thin", "cinematic", "heavy"],
          },
        ],
      },
      {
        title: "Snow",
        controls: [
          {
            id: "weather-snow-density",
            label: "Snow density",
            description: "Controls how many snowflakes appear.",
            kind: "range",
            value: 0.48,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "weather-snow-drift",
            label: "Snow drift",
            description: "Adds sideways movement to falling snow.",
            kind: "range",
            value: 0.32,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "weather-snow-soften",
            label: "Soft snow lighting",
            description: "Softens lighting on snow during snowfall.",
            kind: "toggle",
            value: true,
          },
          {
            id: "weather-cold-haze",
            label: "Cold haze",
            description: "Adds pale atmospheric haze in snowy weather.",
            kind: "range",
            value: 0.28,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "Storms",
        controls: [
          {
            id: "weather-thunder-flash",
            label: "Lightning flash",
            description: "Controls the brightness of lightning flashes.",
            kind: "range",
            value: 0.72,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "weather-storm-darkness",
            label: "Storm darkness",
            description: "Darkens the world during stormy weather.",
            kind: "range",
            value: 0.55,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "weather-wet-surfaces",
            label: "Wet surfaces",
            description: "Adds wet shading to exposed surfaces in rain.",
            kind: "toggle",
            value: true,
          },
          {
            id: "weather-puddle-reflections",
            label: "Puddle reflections",
            description: "Controls reflected highlights in rain puddles.",
            kind: "range",
            value: 0.34,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    id: "time-of-day",
    title: "Time Of Day",
    summary: "Balance dawn, noon, sunset, night exposure, and time transition curves.",
    sections: [
      {
        title: "Dawn",
        controls: [
          {
            id: "time-dawn-warmth",
            label: "Dawn warmth",
            description: "Controls how warm sunrise lighting feels.",
            kind: "range",
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "time-dawn-color",
            label: "Dawn color",
            description: "Sets the main color used at sunrise.",
            kind: "color",
            value: "#ffb08a",
          },
          {
            id: "time-dawn-haze",
            label: "Dawn haze",
            description: "Adds soft haze during sunrise transitions.",
            kind: "range",
            value: 0.36,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "time-dawn-duration",
            label: "Dawn duration",
            description: "Changes how long sunrise color lingers.",
            kind: "range",
            value: 0.42,
            min: 0.1,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "Day And Sunset",
        controls: [
          {
            id: "time-noon-brightness",
            label: "Noon brightness",
            description: "Controls peak daylight brightness at noon.",
            kind: "range",
            value: 0.78,
            min: 0,
            max: 1.5,
            step: 0.01,
          },
          {
            id: "time-sunset-intensity",
            label: "Sunset intensity",
            description: "Controls the strength of sunset coloring.",
            kind: "range",
            value: 0.68,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "time-sunset-color",
            label: "Sunset color",
            description: "Sets the main color used at sunset.",
            kind: "color",
            value: "#ff7a5a",
          },
          {
            id: "time-golden-hour",
            label: "Extended golden hour",
            description: "Keeps warm sunset lighting active for longer.",
            kind: "toggle",
            value: true,
          },
        ],
      },
      {
        title: "Night",
        controls: [
          {
            id: "time-night-exposure",
            label: "Night exposure",
            description: "Controls scene visibility during nighttime.",
            kind: "range",
            value: 0.36,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "time-night-color",
            label: "Night color",
            description: "Sets the base atmospheric color at night.",
            kind: "color",
            value: "#1e2b54",
          },
          {
            id: "time-moon-phase-light",
            label: "Moon phase lighting",
            description: "Varies night lighting by the moon phase.",
            kind: "toggle",
            value: true,
          },
          {
            id: "time-transition-curve",
            label: "Transition curve",
            description: "Chooses how smoothly lighting changes over time.",
            kind: "select",
            value: "smooth",
            options: ["linear", "smooth", "cinematic", "high contrast"],
          },
        ],
      },
    ],
  },
  {
    id: "dimensions",
    title: "Dimensions",
    summary: "Style Overworld, Nether, End, caves, and custom dimension atmospheres.",
    sections: [
      {
        title: "Overworld",
        controls: [
          {
            id: "dimensions-overworld-profile",
            label: "Overworld profile",
            description: "Selects the base atmosphere for the Overworld.",
            kind: "select",
            value: "balanced",
            options: ["vanilla plus", "balanced", "cinematic", "realistic"],
          },
          {
            id: "dimensions-biome-contrast",
            label: "Biome contrast",
            description: "Controls how distinct biome atmospheres feel.",
            kind: "range",
            value: 0.46,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "dimensions-cave-atmosphere",
            label: "Cave atmosphere",
            description: "Adds haze and mood to underground spaces.",
            kind: "range",
            value: 0.52,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "dimensions-height-fog",
            label: "Height based fog",
            description: "Changes fog behavior by world height.",
            kind: "toggle",
            value: true,
          },
        ],
      },
      {
        title: "Nether",
        controls: [
          {
            id: "dimensions-nether-haze",
            label: "Nether haze",
            description: "Controls the dense atmospheric haze in the Nether.",
            kind: "range",
            value: 0.58,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "dimensions-nether-glow",
            label: "Lava glow",
            description: "Adjusts ambient glow from Nether lava.",
            kind: "range",
            value: 0.72,
            min: 0,
            max: 1.5,
            step: 0.01,
          },
          {
            id: "dimensions-nether-color",
            label: "Nether air color",
            description: "Sets the base color of Nether atmosphere.",
            kind: "color",
            value: "#7f2d2a",
          },
          {
            id: "dimensions-basalt-ash",
            label: "Basalt ash falloff",
            description: "Controls ash-like haze around basalt regions.",
            kind: "range",
            value: 0.31,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "End",
        controls: [
          {
            id: "dimensions-end-void-tint",
            label: "Void tint",
            description: "Sets the atmospheric tint for the End void.",
            kind: "color",
            value: "#2f234d",
          },
          {
            id: "dimensions-end-starfield",
            label: "End starfield",
            description: "Shows stars or void specks in the End sky.",
            kind: "toggle",
            value: true,
          },
          {
            id: "dimensions-end-fog",
            label: "End fog depth",
            description: "Controls how much fog fills the End distance.",
            kind: "range",
            value: 0.44,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "dimensions-end-mood",
            label: "End mood",
            description: "Chooses the overall atmosphere grading used in the End.",
            kind: "select",
            value: "tense",
            options: ["clean", "tense", "ethereal", "dark"],
          },
        ],
      },
    ],
  },
  {
    id: "stars",
    title: "Stars",
    summary: "Set star density, twinkle, milky bands, shooting stars, and night clarity.",
    sections: [
      {
        title: "Starfield",
        controls: [
          {
            id: "stars-density",
            label: "Star density",
            description: "Controls how many stars appear at night.",
            kind: "range",
            value: 0.62,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "stars-brightness",
            label: "Star brightness",
            description: "Adjusts the brightness of visible stars.",
            kind: "range",
            value: 0.54,
            min: 0,
            max: 1.5,
            step: 0.01,
          },
          {
            id: "stars-size",
            label: "Star size",
            description: "Changes the apparent size of stars.",
            kind: "range",
            value: 0.28,
            min: 0.05,
            max: 1,
            step: 0.01,
          },
          {
            id: "stars-color-variation",
            label: "Color variation",
            description: "Adds subtle color differences between stars.",
            kind: "range",
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        title: "Motion And Detail",
        controls: [
          {
            id: "stars-twinkle",
            label: "Twinkle",
            description: "Controls how much stars flicker over time.",
            kind: "range",
            value: 0.18,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "stars-shooting-stars",
            label: "Shooting stars",
            description: "Enables occasional shooting stars at night.",
            kind: "toggle",
            value: true,
          },
          {
            id: "stars-shooting-frequency",
            label: "Shooting frequency",
            description: "Controls how often shooting stars appear.",
            kind: "range",
            value: 0.16,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "stars-constellation-hints",
            label: "Constellation hints",
            description: "Adds faint guide lines between selected stars.",
            kind: "toggle",
            value: false,
          },
        ],
      },
      {
        title: "Milky Band",
        controls: [
          {
            id: "stars-milky-band",
            label: "Milky band",
            description: "Shows a soft galaxy band across the night sky.",
            kind: "toggle",
            value: true,
          },
          {
            id: "stars-milky-opacity",
            label: "Milky opacity",
            description: "Controls how visible the galaxy band is.",
            kind: "range",
            value: 0.26,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "stars-milky-color",
            label: "Milky color",
            description: "Sets the tint of the galaxy band.",
            kind: "color",
            value: "#d7d9ff",
          },
          {
            id: "stars-night-clarity",
            label: "Night clarity",
            description: "Chooses how clear or hazy the night sky feels.",
            kind: "select",
            value: "clear",
            options: ["hazy", "clear", "crisp", "deep space"],
          },
        ],
      },
    ],
  },
  {
    id: "aurora",
    title: "Aurora",
    summary: "Design polar lights with layered color, movement, intensity, and biome rules.",
    sections: [
      {
        title: "Presence",
        controls: [
          {
            id: "aurora-enabled",
            label: "Aurora",
            description: "Toggles aurora lights in the night sky.",
            kind: "toggle",
            value: true,
          },
          {
            id: "aurora-frequency",
            label: "Frequency",
            description: "Controls how often auroras appear.",
            kind: "range",
            value: 0.22,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "aurora-biome-rule",
            label: "Biome rule",
            description: "Sets where auroras are allowed to appear.",
            kind: "select",
            value: "cold biomes",
            options: ["all nights", "cold biomes", "high altitude", "end dimension"],
          },
          {
            id: "aurora-weather-filter",
            label: "Hide during storms",
            description: "Hides auroras during stormy weather.",
            kind: "toggle",
            value: true,
          },
        ],
      },
      {
        title: "Color",
        controls: [
          {
            id: "aurora-primary-color",
            label: "Primary color",
            description: "Sets the main color of aurora bands.",
            kind: "color",
            value: "#4dffb0",
          },
          {
            id: "aurora-secondary-color",
            label: "Secondary color",
            description: "Sets the accent color of aurora bands.",
            kind: "color",
            value: "#7d8cff",
          },
          {
            id: "aurora-color-shift",
            label: "Color shift",
            description: "Controls how much aurora colors blend and shift.",
            kind: "range",
            value: 0.34,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "aurora-intensity",
            label: "Intensity",
            description: "Adjusts how bright auroras appear.",
            kind: "range",
            value: 0.48,
            min: 0,
            max: 1.5,
            step: 0.01,
          },
        ],
      },
      {
        title: "Shape And Motion",
        controls: [
          {
            id: "aurora-band-count",
            label: "Band count",
            description: "Sets the number of visible aurora curtains.",
            kind: "range",
            value: 3,
            min: 1,
            max: 8,
            step: 1,
          },
          {
            id: "aurora-wave-speed",
            label: "Wave speed",
            description: "Controls how quickly aurora waves move.",
            kind: "range",
            value: 0.26,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "aurora-curtain-height",
            label: "Curtain height",
            description: "Changes how tall aurora curtains reach.",
            kind: "range",
            value: 0.57,
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            id: "aurora-soft-edges",
            label: "Soft edges",
            description: "Softens the edges of aurora curtains.",
            kind: "toggle",
            value: true,
          },
        ],
      },
    ],
  },
] as const;
